version: "2"
services:
  app:
    container_name: synaos-es-api
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"